### ISSUE TITLE
Reserved Keywords

### ISSUE THREAD

**Issue by jon-wesneski** [jonwesneski/test_framework#11]
These are objects that are defined by the end2 framework and the tester can decide to use them in a test or not; it is optional. We current have to objects that are created by end2: logger and package_objects. Python has a concept called named kwargs, which means the end user has to define the name of the parameter or it cannot be used. 
```
def func(a, * b):
    pass
    
func(1, 2)  # This fails because 2nd arg is not named; should be func(1, b=2)
```

Make these named kwargs optional, by doing an inspect at runtime on the test function and seeing which named kwargs are defined. The ones that are defined will be passed in the func at run time

examples:
```
def test_1():
   pass  # no test parameters and no reserved word parameters 

def test_2(a):
   pass  # 1 test parameter and no reserved word parameters 

def test_3(a, * logger, package_object):
   pass  # 1 test parameters and 2 reserved word parameters 

def test_4(* logger, package_object):
   pass  # only reserved word parameters 

def test_4(* a):
   pass  # will fail because 'a' is not a reserved word

def test_4(**kwargs):
   pass  # will have however many test parameters their are and all of the reserved words

def test_4(logger):
   pass  # will fail because this causes a conflict with the reserved word "logger"; create a new exception around naming conflict
```

Or possibly do just 1 reserved word. Maybe call it `test` and this test_object will hold all the reserved end2 words:
- logger
- package_object
- done (a callback to wait for test to be done; for event passed clients)
- step (a callback to record the steps taken, takes a descriptive step name, callback and callback args, assertion Callback; this will also save start, end, duration time  of step)

**Comment by jonwesneski** [comment]
Might add:
"step (a callback to record the steps taken, takes a descriptive step name, callback and callback args, assertion Callback; this will also save start, end, duration time of step)"

in another ticket
